export { default as Header } from "./Header"
export { default as Menu } from "./Menu"
export { default as SlideBar } from "./SlideBar"
export { default as Slider } from "./Slider"
export { default as Footer } from "./Footer"